feat:pull1个
Jeffmen/gitDemo pull request #1
Opened 2022-05-10 07:53 UTC by Jeffmen

pull1

2022-05-10 07:57 UTC, jomatto commented on main.dart
> +class Pull1 {
Good from jomatto

2022-05-10 07:57 UTC, jomatto approved these changes

2022-05-10 08:09 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
good2 from jomato

2022-05-10 08:40 UTC, Jeffmen commented on main.dart
> +class Pull1 {
热play

2022-05-10 08:41 UTC, Daojiand commented on main.dart
> +
need some code from daojiand

2022-05-10 08:42 UTC, Daojiand commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
don/t need from daojiand

2022-05-10 09:37 UTC, Daojiand commented on main.dart
> +class Pull1 {
from daojiang

2022-05-10 09:42 UTC, Jeffmen commented on main.dart
> +class Pull1 {
> Good from jomatto

额外

2022-05-10 09:43 UTC, Jeffmen commented on main.dart
> +class Pull1 {
> 热play
> 

我是

2022-05-10 09:45 UTC, Jeffmen commented
稻米奇妙的

2022-05-10 09:48 UTC, jomatto submitted a review, later dismissed

2022-05-11 07:29 UTC, Jeffmen reviewed
稻香樟

2022-05-11 14:27 UTC, jomatto requested changes
request changes

2022-05-12 08:17 UTC, jomatto commented on main.dart
> +class Pull1 {
reply1

2022-05-12 08:17 UTC, jomatto commented on main.dart
> +class Pull1 {
> Good from jomatto的
reply2

2022-05-12 10:01 UTC, jomatto commented on main.dart
> +  fun fun1(){
funct

2022-05-12 10:03 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
import

2022-05-13 08:57 UTC, Jeffmen commented
from jeffmen

2022-05-13 08:58 UTC, Jeffmen commented
稻米奇妙的

2022-05-13 08:58 UTC, Jeffmen reviewed
from mobile

2022-05-13 09:06 UTC, Jeffmen commented
> from mobile
> 

我

2022-05-13 13:57 UTC, jomatto reviewed
from gitown

2022-05-13 14:11 UTC, jomatto requested changes
request changes

2022-05-13 14:11 UTC, jomatto approved these changes, later dismissed
approve

2022-05-21 08:44 UTC, jomatto commented
稻米

2022-05-21 09:43 UTC, jomatto commented
> pull1
我

2022-05-21 09:49 UTC, jomatto commented on main.dart
> +  fun fun1(){
5

2022-05-21 09:56 UTC, jomatto commented on main.dart
> +  fun fun1(){
稻米奇妙

2022-05-21 15:47 UTC, jomatto commented on main.dart
> +class Pull1 {
> > 热play
> > 
> 
> 我是
VTKJVSXQKY8J

2022-05-21 15:51 UTC, jomatto commented on main.dart
> +class Pull1 {
> Good from jomatto
我

2022-05-22 08:20 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
51速度

2022-05-22 09:42 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
comment5

2022-05-22 09:49 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
commet6

2022-05-22 09:52 UTC, jomatto commented on main.dart
> +
come

2022-05-22 09:52 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
7

2022-05-22 09:56 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
1

2022-05-22 10:11 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
1

2022-05-22 10:17 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
2

2022-05-22 10:24 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
e

2022-05-22 10:25 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
5

2022-05-22 10:26 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
异

2022-05-22 10:46 UTC, jomatto commented on main.dart
> +
润

2022-05-22 12:55 UTC, jomatto reviewed
还有个

2022-05-22 12:55 UTC, jomatto commented
c哦mmen

2022-05-22 13:00 UTC, jomatto commented
海盗

2022-05-22 13:48 UTC, jomatto commented on main.dart
> +  fun fun1(){
56

2022-05-22 13:49 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
给个个

2022-05-23 09:28 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
- [ ] - 啊

2022-05-23 09:30 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
- [ ] uu

2022-05-23 13:27 UTC, jomatto commented on main.dart
> +
稻香

2022-05-23 13:40 UTC, jomatto commented on main.dart
> +class Pull1 {
还好

2022-05-23 13:42 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
58我

2022-05-23 13:45 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
稻香

2022-05-23 13:46 UTC, jomatto commented on main.dart
> +class Pull1 {
58的

2022-05-23 13:49 UTC, jomatto commented on main.dart
> +class Pull1 {
> from daojiang
呃呃

2022-05-23 13:49 UTC, jomatto commented on main.dart
> +class Pull1 {
稻米奇妙

2022-05-23 14:14 UTC, jomatto commented on main.dart
> +class Pull1 {
> > 热play
> > 
> 
> 我是

2022-05-23 14:27 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
58的话

2022-05-23 14:33 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
444我

2022-05-23 14:33 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
英语

2022-05-23 14:34 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
也一样

2022-05-23 14:34 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
很好哈

2022-05-23 14:35 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
还好h

2022-05-23 14:35 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
还好h

2022-05-23 14:35 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
很好h

2022-05-23 14:36 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
还好

2022-05-23 14:42 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
用英语

2022-05-23 14:42 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
uuuu

2022-05-23 14:59 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
给个个

2022-05-23 14:59 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
580

2022-05-23 15:19 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
很好

2022-05-23 15:19 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
人儿

2022-05-23 15:19 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
> 很好
人儿

2022-05-23 15:22 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
还好h

2022-05-23 15:22 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
人儿

2022-05-23 15:23 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
还好还好

2022-05-23 15:23 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
润文

2022-05-23 15:24 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
还好

2022-05-23 15:26 UTC, jomatto commented on main.dart
> -import 'com/camp/widget/no_scroll_behavior.dart';
还好h

2022-05-23 15:46 UTC, jomatto commented on main.dart
> +class Pull1 {
稻妻

2022-05-23 15:47 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
方法

2022-05-24 08:27 UTC, Daojiand commented on main.dart
> +class Pull1 {
> > 热play
> > 
> 
> 我是
ggg

2022-05-24 08:27 UTC, Daojiand commented on main.dart
> +class Pull1 {
> 稻妻
ggg

2022-05-24 08:28 UTC, Daojiand commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
ugh

2022-05-24 08:28 UTC, Daojiand reviewed
hhhh

2022-05-30 09:03 UTC, jomatto approved these changes
good

2022-05-31 13:45 UTC, jomatto commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
> don/t need from daojiand

VTKJVSXQKY8J

2022-06-07 14:03 UTC, jomatto commented
> pull1

VTKJVSXQKY8J

2022-06-07 14:03 UTC, jomatto commented
> good

#哦哦

2022-06-07 14:03 UTC, jomatto commented
> 还有个

#了

2022-06-07 14:13 UTC, Jeffmen commented on main.dart
> +class Pull1 {
海很

2022-06-07 14:15 UTC, Jeffmen commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
稻子帐号

2022-06-08 02:41 UTC, Jeffmen commented
> from mobile了

一样

2022-06-08 08:55 UTC, jomatto commented
我们

2022-06-12 09:03 UTC, jomatto commented
海

2022-06-13 10:56 UTC, Jeffmen commented on route_path.dart
> +import 'com/camp/page/web/pull1.dart';
今天

2022-06-13 14:06 UTC, closed without merging